version: '3.9'
services:
  client:
    build:
      context: "./client"
      dockerfile: "Dockerfile.dev"
    container_name: "Client"
    ports:
      - "${CLIENT_PORT}:5173"
    volumes:
      - "./client:/app"
      - "/app/node_modules"
  backend:
    build:
      context: "./server"
      dockerfile: "Dockerfile.dev"
    container_name: "Server"
    restart: "always"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
    ports:
      - "${SERVER_PORT}:5000"
    volumes:
      - "./server:/app"
    depends_on:
      - "database"
  database:
    image: postgres:16-alpine
    container_name: "Database"
    restart: "always"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - "./db:/docker-entrypoint-initdb.d"
      - "./db/database_instance:/var/lib/postgresql/data"