version: '3.9'
services:
  database:
    image: postgres:15-alpine
    container_name: "Database"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data