CREATE TABLE IF NOT EXISTS Users (
  id SERIAL PRIMARY KEY,
  email VARCHAR(60) NOT NULL,
  password VARCHAR(130) NOT NULL
);

CREATE TABLE IF NOT EXISTS Refresh_Tokens (
  user_id INT PRIMARY KEY,
  token VARCHAR(170) NOT NULL
);